[phases.setup]
nixPkgs = ["python39", "nodejs_18", "python39Packages.pip"]

[phases.install]
cmds = [
    "npm ci",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
