[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "gorzen-ingestion"

[services.gorzen-ingestion]
source = "."
